import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useState } from "react";
import Recorder from '../components/Recorder';
import SelectDevice from '../components/SelectDevice';
import Grid from '../components/Grid';
import Sidebar from '../components/Sidebar';

const Home: NextPage = () => {
  const [videoDeviceId, setVideoDeviceId] = useState();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="grid bg-gray-800 h-screen" style={{ gridTemplateColumns: "20% 80%" }}>
          <div>
            <Sidebar />
            <SelectDevice setVideoDeviceId={setVideoDeviceId} />
          </div>
          <div>
            <Recorder videoDeviceId={videoDeviceId} />
            <Grid />
          </div>
        </div>
      </main>
    </div>
  )
}

export default Home
